language: node_js
services:
- redis-server
node_js:
- node
install:
- npm install
script:
- npm test
deploy:
  provider: npm
  email: andreas@softbrix.se
  api_key:
    secure: QrAVi4w8NTL9FlBndEuKC+wmmGqyvztgxDcHpyGDTWKn8N1bNBS2SMc8EIKNmzXzeZQEY46Rgvp/nk8VwreqP4rugCcNw01QpTHGV94OsKXpAxiKR2SfycGQr0ZC8pASgQ9XKqrjMvKkBfGGwymGAawkQjw/m2gQSXQRntc4MkO59FfzE8hF48x2s7WYqRNIawkGx/RU6WQQpiPmnlaoTGIVoO/QTUcXoLehnNbxFmfiCR/NGM3XL8yR7l1DujBRyZaSilVQTUcSmIfWOHyCzc3ygO4athAo9cLj161DvCSVD9GX0/xP7gmjFR87qV9sRntnqMhFZVMc+cpWPzrXaWX2vN5hxs4lLP+9dUrrSDFFTHF69k51HUgcgwmX6Io/S6DM8+KD73B9IpV6QnapjTYKRiPY3hJ8KWo3sLo1onQuclz0NBBDJiBww/1mrhqdBaaiggsn5vcspgHeg8B5eju0THy8ugtCrt24QjsCR9f8hLElS3cSR+V3vkJsG0rIxyK8NXI+WlMzmqQY+MKCGTtuq3nLtgx85akFG7sfmFCI7Nr6DGwDR/yba3pYVTx8CXL91EBEGvPmO7WWUZnfgK6yHdsPGbO+eD1v9veyQ868UhxI5pxiL6g5lwzU9gDC+vw5kOj/0xF4RkNv4YymHRwG4otXVaci0/KMk4Lyckg=
  on:
    tags: true
    repo: softbrix/vemdalen_index
