language: node_js
services:
- redis-server
node_js:
- node
install:
- npm install
script:
- npm test --exit
deploy:
  provider: npm
  email: andreas@softbrix.se
  api_key:
    secure: Yp2jZ9X5+WM7s/YlhRLsuEsUuhkinZPkPVBhQv7D8Pq+h19vUNqfG8zzbxFsqOEQtd04v/oFJZNkJgS8tdx23vSVVci7G82V2THCZxkYNNlMhXUqQfyeZ2GFohowub3BkFm1wCRmVYt3UIO3qVYzEavGANLo4P35IiWydtnQ0qyZIp/ay0r5LzFZRxiPD9/0n7fHp7qrMCaIkLytDKrK4CkrIAbvtmGvjUWPWiZddxfFwRAdajTQ6NxXNfj/wCoPz834IGUIsS9Pm482U58KIx5JcGOoh+A+IfyUgJP/lE1L6ha0mexQ5YybXSsqh7Bx22AFjD7wprOuqquIgb1x8XiK2BrSydL/Zs85dKKC3rgIreM46h27d1vqZffS7cb1S7Oav0K3ag7tbeWgdT8Ld+NS+MMtMT/xfUkfvxb9g+Lb2u/vVDZAKW6lsUPtpYhHj6l/tYu//7pqRs9yXuGROp90hyQxemFNTVkQT02qbDToS+gbGulJtpIZZmtBtKQVr2wIBiKadS35VVwDARj67Eu0WaAXesj+3GdDtTIVLFpm7biyUI34SlKv8HtwH6Sg23X5KtNPVQjj9AZViV/kEk2IftPghubErx80NqE5h3GikcrBZL4AkqcQOglLHf82tD4f+zdiPWg4H3JIJJlqm/1PFflACvC8nMJoOJxFjEE=
  on:
    tags: true
    repo: softbrix/vemdalen_index
